on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: extract git commit data 
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Print git commit data
        run: |
          echo "Get author info"
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
