on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Test
        run: echo "done"
      - name: Raise PR
        uses: vsoch/create-pull-request@main
        with:
          branch: "first"
          base: main
          title: "demo for auto PR"
          delete-branch: false
