on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: sabarees48/myrepo@v1.x
