on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: extract git commit data 
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "first"
          base: main
          title: "demo for auto PR"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}*>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}*>
          body:
            This is automatic PR creation
          token: ${{ secrets.SECRET_TOKEN}}
          delete-branch: false
