on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Raise PR
        uses: myrepo/create-pull-request@v2
        with:
          branch: "first"
          base: main
          title: "demo for auto PR"
          delete-branch: false
