on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Test
        run: echo "done"
