on:
  push:
    branches:
      - main
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Test
        run: echo "done"
      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "first"
          base: main
          title: "demo for auto PR"
          token: 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
          delete-branch: false
